# Generated by Django 2.2.12 on 2022-10-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=52)),
                ('Lname', models.CharField(max_length=52)),
                ('Age', models.IntegerField(max_length=52)),
                ('Phone', models.CharField(max_length=43)),
            ],
        ),
    ]
